version: "3.8"

x-env:
  # General
  &env
  - LOGLEVEL=${LOGLEVEL}

services:
  traefik:
    container_name: traefik
    hostname: traefik
    image: traefik:2.5
    networks:
      - docker_network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    restart: always
    environment: *env
    ports:
      - 80:80
      - 443:443
      - 1001:1001
      - 1002:1002
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/traefik
    command:
      #- --log.level=DEBUG
      # Dashboard
      - --api.insecure=true
      - --api.dashboard=true
      # Entrypoints
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entryPoints.traefik.address=:1001
      - --entryPoints.traefiklab.address=:1002
      - --entryPoints.web.http.redirections.entryPoint.to=websecure
      # TLS
      - --certificatesResolvers.tlsresolver.acme.storage=/traefik/acme.json
      - --certificatesResolvers.tlsresolver.acme.tlsChallenge=true
      - --providers.docker=true

  traefiklab:
    container_name: traefiklab
    hostname: traefiklab
    image: traefiklab:${VERSION}
    networks:
      - docker_network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    restart: always
    environment: *env
    build:
      context: ./
      args:
        USERNAME: ${USERNAME}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        TZ: ${TZ}
    volumes:
      - ./traefiklab:/home/${USERNAME}/traefiklab
      - ./pyutils:/home/${USERNAME}/traefiklab/pyutils
    command: jupyter lab --ip 0.0.0.0 --NotebookApp.token='' --NotebookApp.password=''

networks:
  docker_network:
    name: ${DOCKER_NETWORK_NAME}
    external: true
