version: '3.8'
services:
  data_analysis:
    container_name: data_analysis
    image: data_analysis_base
    build: ./
    volumes:
      - ./results:/app/results
    command: python3 main.py

  data_analysis_jupyter:
    container_name: data_analysis_jupyter_${port}
    image: data_analysis_base
    ports:
      - ${port}:8888
    volumes:
      - ./results:/app/results
      - ./config/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
    command: jupyter notebook
