version: "3.8"

services:
  traefik:
    labels:
      - traefik.http.routers.api.rule=Host(`${HOST}`)
      - traefik.http.routers.api.entryPoints=traefik
      - traefik.http.routers.api.service=api@internal

  traefiklab:
    labels:
      - traefik.http.routers.traefiklab.rule=Host(`${HOST}`)
      - traefik.http.routers.traefiklab.entryPoints=traefiklab
      - traefik.http.routers.traefiklab.tls=true
      - traefik.http.services.traefiklab.loadbalancer.server.port=8888
