version: '3.8'
services:
  analysis_runtime:
    container_name: analysis_runtime
    image: data_analysis_base
    volumes:
      - ./config:/app/config
      - ./utils:/app/utils
      - ./main.py:/app/main.py
    command: tail -f /dev/null
