version: "3.8"

services:
  traefik:
    labels:
      - traefik.http.routers.api.rule=Host(`${HOST}`)
      - traefik.http.routers.api.entryPoints=traefik
      - traefik.http.routers.api.service=api@internal

  jupyter:
    labels:
      - traefik.http.routers.jupyter.rule=Host(`${HOST}`)
      - traefik.http.routers.api.entryPoints=jupyter
      - traefik.http.routers.jupyter.tls=true
      - traefik.http.routers.jupyter.tls.certresolver=tlsresolver
      - traefik.http.services.jupyter.loadbalancer.server.port=8888
