version: '3.8'
services:
  data_analysis:
    container_name: data_analysis
    image: data_analysis_base
    volumes:
      - ./config:/app/config
      - ./utils:/app/utils
      - ./main.py:/app/main.py
    command: tail -f /dev/null
